Added functionality to access terminal window height (number of lines)
AdaCore/gnatcoll-core pull request #81
Opened 2023-10-19 15:09 UTC by fastrgv

For several of my apps I needed the window height.  This change has been tested on OSX, Windows, and several flavors of linux.
See, for example, "RetroArcade". This is one of my projects on GitHub.

2023-10-20 08:10 UTC, setton requested changes
Thank you very much for this contribution. I have left a few comments - only stylistic, the code itself looks good to me. Let us know if you're happy to make those changes.

2023-10-20 08:10 UTC, setton commented on src/terminals.c
> +      //return (int)csbiInfo.dwSize.X; // buffer width
Please remove the commented-out line. (Same comment on line 148)

2023-10-20 08:10 UTC, setton commented on src/terminals.c
> +						-csbiInfo.srWindow.Left + 1); // window width
The indentation of this line is off - please remove the tabs (same comment for line 150)

2023-10-20 08:10 UTC, setton commented on src/gnatcoll-terminal.ads
> +
Please remove these extra lines.

2023-10-20 08:10 UTC, setton commented on src/gnatcoll-terminal.ads
> +
Please remove one of these blank lines.

2023-10-20 08:10 UTC, setton commented on src/gnatcoll-terminal.adb
> +
Please remove the extra blank lines - there should be at most one blank line as separation. (Same goes for lines 452-453.)

2023-10-20 10:30 UTC, t-14 reviewed
As a general comment, can you also add a new test exercising the additional code?

2023-10-20 12:25 UTC, fastrgv commented
Ok, I think all suggested changes have been made. And I attached a test driver in this message.

[testwin_adb.txt](https://github.com/AdaCore/gnatcoll-core/files/13054161/testwin_adb.txt)

2023-10-21 21:56 UTC, t-14 commented
> And I attached a test driver in this message.

Thanks, but this needs to be added as a new test case in `testsuite/tests/terminal`.

2023-10-21 23:07 UTC, fastrgv commented
Ok. I just added it to ~testsuite/tests/terminal/testlines.adb

2024-03-25 10:43 UTC, Jicquel commented
Hello @fastrgv, thank you for your contribution! Your commits have been squashed and merged here: https://github.com/AdaCore/gnatcoll-core/commit/724c8dba486c913075858e21074223940795f22f.

2024-03-25 10:43 UTC, closed without merging